### ISSUE TITLE
Env file should contains all the Database configuration and mention Docker-Compose relation

### ISSUE THREAD

**Issue by disk91** [helium/console#412]
In the current .env file we have only
```
DATABASE_DB=console
DATABASE_HOST=postgres
```
I think we should have:
```
# make sure your setting matches the DockerCompose
DATABASE_DB=console
DATABASE_HOST=postgres
DATABASE_USER=console
DATABASE_PASSWORD=xxx
```

I also propose to add in docker-compose.yml file
```
postgres:
    image: postgres
    container_name: helium_postgres
    restart: always
    environment:
        - POSTGRES_DB=console
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=console
    volumes:
      - "./data/postgres/:/var/lib/postgresql/data"
```
